apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  tls:
  - hosts:
    - hfcdevops.xyz
    secretName: devops-tls
  rules:
    - host: hfcdevops.xyz
      http:
        paths:
          - path: /api/healthmon/?(.*)
            pathType: Prefix
            backend:
              service:
                name: healthmon-svc
                port:
                  number: 3000
          - path: /api/position/?(.*)
            pathType: Prefix
            backend:
              service:
                name: posapi-svc
                port:
                  number: 3000   
          - path: /api/waypoints/?(.*)
            pathType: Prefix
            backend:
              service:
                name: waypointstore-svc
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-svc
                port:
                  number: 3000