apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: hfcdevops/posplot-client
          env:
            - name: HEALTHMON_URL
              value: 'http://healthmon-svc:3000/api/healthmon'
            - name: REACT_APP_GITHUB_URL
              value: https://github.com/login/oauth/authorize
            - name: REACT_APP_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-secret 
                  key: GITHUB_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000