apiVersion: apps/v1
kind: Deployment
metadata:
  name: waypointstore-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waypointstore-mongo
  template:
    metadata:
      labels:
        app: waypointstore-mongo
    spec:
      containers:
      - name: waypointstore-mongo
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: waypointstore-mongo-svc
spec:
  selector:
    app: waypointstore-mongo
  ports:
  - name: db
    protocol: TCP
    port: 27017
    targetPort: 27017

