name: deploy-oauthmgr

on:
  push:
    branches:
      - master 
    paths:
      - 'oauthmgr/**'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - run: cd oauthmgr && docker build -t hfcdevops/oauth-manager . 
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push hfcdevops/oauth-manager
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save posplot-k8s-demo
      - run: kubectl rollout restart deployment oauth-depl
