name: deploy-posapi

on:
  push:
    branches:
      - master 
    paths:
      - 'posapi/**'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - run: cd posapi && docker build -t hfcdevops/posapi . 
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push hfcdevops/posapi 
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save posplot-k8s-demo
      - run: kubectl rollout restart deployment posapi-depl
