name: tests-posapi

on:
  pull_request:
    paths: 
      - 'posapi/**'
jobs:
  buinds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd posapi && npm install && npm run test:ci
